/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "cd_rpc_prot.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
printmessage_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, PRINTMESSAGE,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudevicegetcount_1(int_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cuDeviceGetCount, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cuinit_1(int arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuInit,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudrivergetversion_1(int_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cuDriverGetVersion, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cudeviceget_1(int arg1, int_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuDeviceGet,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudevicegetname_1(int arg1, str_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuDeviceGetName,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_str_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudevicetotalmem_1(int arg1, u64_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuDeviceTotalMem,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_u64_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudevicegetattribute_1(int arg1, int arg2, int_result *clnt_res,  CLIENT *clnt)
{
	rpc_cudevicegetattribute_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, rpc_cuDeviceGetAttribute, (xdrproc_t) xdr_rpc_cudevicegetattribute_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudevicegetuuid_1(int arg1, uuid_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuDeviceGetUuid,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_uuid_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cuctxgetcurrent_1(ptr_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cuCtxGetCurrent, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cuctxsetcurrent_1(uint64_t arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuCtxSetCurrent,
		(xdrproc_t) xdr_uint64_t, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudeviceprimaryctxretain_1(int arg1, ptr_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuDevicePrimaryCtxRetain,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cumodulegetfunction_1(uint64_t arg1, char *arg2, ptr_result *clnt_res,  CLIENT *clnt)
{
	rpc_cumodulegetfunction_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, rpc_cuModuleGetFunction, (xdrproc_t) xdr_rpc_cumodulegetfunction_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cugetexporttable_1(rpc_uuid uuid, ptr_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuGetExportTable,
		(xdrproc_t) xdr_rpc_uuid, (caddr_t) &uuid,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cumemalloc_1(uint64_t arg1, ptr_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuMemAlloc,
		(xdrproc_t) xdr_uint64_t, (caddr_t) &arg1,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cuctxgetdevice_1(int_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cuCtxGetDevice, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cumemcpyhtod_1(uint64_t arg1, mem_data arg2, int *clnt_res,  CLIENT *clnt)
{
	rpc_cumemcpyhtod_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, rpc_cuMemcpyHtoD, (xdrproc_t) xdr_rpc_cumemcpyhtod_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_culaunchkernel_1(uint64_t arg1, u_int arg2, u_int arg3, u_int arg4, u_int arg5, u_int arg6, u_int arg7, u_int arg8, uint64_t arg9, mem_data arg10, int *clnt_res,  CLIENT *clnt)
{
	rpc_culaunchkernel_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	arg.arg7 = arg7;
	arg.arg8 = arg8;
	arg.arg9 = arg9;
	arg.arg10 = arg10;
	return (clnt_call (clnt, rpc_cuLaunchKernel, (xdrproc_t) xdr_rpc_culaunchkernel_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_hidden_get_device_ctx_1(int arg1, ptr_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_hidden_get_device_ctx,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_hidden_get_module_1(uint64_t arg2, uint64_t arg3, uint64_t arg4, int arg5, ptr_result *clnt_res,  CLIENT *clnt)
{
	rpc_hidden_get_module_1_argument arg;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	return (clnt_call (clnt, rpc_hidden_get_module, (xdrproc_t) xdr_rpc_hidden_get_module_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_hidden_1_1_1(ptr_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_hidden_1_1, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_hidden_1_3_1(uint64_t arg1, uint64_t arg2, void *clnt_res,  CLIENT *clnt)
{
	rpc_hidden_1_3_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, rpc_hidden_1_3, (xdrproc_t) xdr_rpc_hidden_1_3_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_hidden_1_5_1(ptr_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_hidden_1_5, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_hidden_2_1_1(uint64_t arg1, void *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_hidden_2_1,
		(xdrproc_t) xdr_uint64_t, (caddr_t) &arg1,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_hidden_3_0_1(int arg1, uint64_t arg2, uint64_t arg3, int *clnt_res,  CLIENT *clnt)
{
	rpc_hidden_3_0_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	return (clnt_call (clnt, rpc_hidden_3_0, (xdrproc_t) xdr_rpc_hidden_3_0_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_hidden_3_2_1(int arg1, uint64_t arg2, ptr_result *clnt_res,  CLIENT *clnt)
{
	rpc_hidden_3_2_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, rpc_hidden_3_2, (xdrproc_t) xdr_rpc_hidden_3_2_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}
