/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cd_rpc_prot.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_printmessage_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (printmessage_1_svc(*argp, result, rqstp));
}

int
_rpc_cudevicegetcount_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudevicegetcount_1_svc(result, rqstp));
}

int
_rpc_cuinit_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cuinit_1_svc(*argp, result, rqstp));
}

int
_rpc_cudrivergetversion_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudrivergetversion_1_svc(result, rqstp));
}

int
_rpc_cudeviceget_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudeviceget_1_svc(*argp, result, rqstp));
}

int
_rpc_cudevicegetname_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudevicegetname_1_svc(*argp, result, rqstp));
}

int
_rpc_cudevicetotalmem_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudevicetotalmem_1_svc(*argp, result, rqstp));
}

int
_rpc_cudevicegetattribute_1 (rpc_cudevicegetattribute_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudevicegetattribute_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_rpc_cudevicegetuuid_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudevicegetuuid_1_svc(*argp, result, rqstp));
}

int
_rpc_cuctxgetcurrent_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cuctxgetcurrent_1_svc(result, rqstp));
}

int
_rpc_cuctxsetcurrent_1 (uint64_t  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cuctxsetcurrent_1_svc(*argp, result, rqstp));
}

int
_rpc_cudeviceprimaryctxretain_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudeviceprimaryctxretain_1_svc(*argp, result, rqstp));
}

int
_rpc_cumodulegetfunction_1 (rpc_cumodulegetfunction_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cumodulegetfunction_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_rpc_cugetexporttable_1 (rpc_uuid  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cugetexporttable_1_svc(*argp, result, rqstp));
}

int
_rpc_cumemalloc_1 (uint64_t  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cumemalloc_1_svc(*argp, result, rqstp));
}

int
_rpc_cuctxgetdevice_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cuctxgetdevice_1_svc(result, rqstp));
}

int
_rpc_cumemcpyhtod_1 (rpc_cumemcpyhtod_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cumemcpyhtod_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_rpc_culaunchkernel_1 (rpc_culaunchkernel_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_culaunchkernel_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, argp->arg6, argp->arg7, argp->arg8, argp->arg9, argp->arg10, result, rqstp));
}

int
_rpc_hidden_get_device_ctx_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_get_device_ctx_1_svc(*argp, result, rqstp));
}

int
_rpc_hidden_get_module_1 (rpc_hidden_get_module_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_get_module_1_svc(argp->arg2, argp->arg3, argp->arg4, argp->arg5, result, rqstp));
}

int
_rpc_hidden_1_1_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_1_1_1_svc(result, rqstp));
}

int
_rpc_hidden_1_3_1 (rpc_hidden_1_3_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_1_3_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_rpc_hidden_1_5_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_1_5_1_svc(result, rqstp));
}

int
_rpc_hidden_2_1_1 (uint64_t  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_2_1_1_svc(*argp, result, rqstp));
}

int
_rpc_hidden_3_0_1 (rpc_hidden_3_0_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_3_0_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_rpc_hidden_3_2_1 (rpc_hidden_3_2_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_3_2_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

void
rpc_cd_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *printmessage_1_arg;
		int rpc_cuinit_1_arg;
		int rpc_cudeviceget_1_arg;
		int rpc_cudevicegetname_1_arg;
		int rpc_cudevicetotalmem_1_arg;
		rpc_cudevicegetattribute_1_argument rpc_cudevicegetattribute_1_arg;
		int rpc_cudevicegetuuid_1_arg;
		uint64_t rpc_cuctxsetcurrent_1_arg;
		int rpc_cudeviceprimaryctxretain_1_arg;
		rpc_cumodulegetfunction_1_argument rpc_cumodulegetfunction_1_arg;
		rpc_uuid rpc_cugetexporttable_1_arg;
		uint64_t rpc_cumemalloc_1_arg;
		rpc_cumemcpyhtod_1_argument rpc_cumemcpyhtod_1_arg;
		rpc_culaunchkernel_1_argument rpc_culaunchkernel_1_arg;
		int rpc_hidden_get_device_ctx_1_arg;
		rpc_hidden_get_module_1_argument rpc_hidden_get_module_1_arg;
		rpc_hidden_1_3_1_argument rpc_hidden_1_3_1_arg;
		uint64_t rpc_hidden_2_1_1_arg;
		rpc_hidden_3_0_1_argument rpc_hidden_3_0_1_arg;
		rpc_hidden_3_2_1_argument rpc_hidden_3_2_1_arg;
	} argument;
	union {
		int printmessage_1_res;
		int_result rpc_cudevicegetcount_1_res;
		int rpc_cuinit_1_res;
		int_result rpc_cudrivergetversion_1_res;
		int_result rpc_cudeviceget_1_res;
		str_result rpc_cudevicegetname_1_res;
		u64_result rpc_cudevicetotalmem_1_res;
		int_result rpc_cudevicegetattribute_1_res;
		uuid_result rpc_cudevicegetuuid_1_res;
		ptr_result rpc_cuctxgetcurrent_1_res;
		int rpc_cuctxsetcurrent_1_res;
		ptr_result rpc_cudeviceprimaryctxretain_1_res;
		ptr_result rpc_cumodulegetfunction_1_res;
		ptr_result rpc_cugetexporttable_1_res;
		ptr_result rpc_cumemalloc_1_res;
		int_result rpc_cuctxgetdevice_1_res;
		int rpc_cumemcpyhtod_1_res;
		int rpc_culaunchkernel_1_res;
		ptr_result rpc_hidden_get_device_ctx_1_res;
		ptr_result rpc_hidden_get_module_1_res;
		ptr_result rpc_hidden_1_1_1_res;
		ptr_result rpc_hidden_1_5_1_res;
		int rpc_hidden_3_0_1_res;
		ptr_result rpc_hidden_3_2_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case PRINTMESSAGE:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_printmessage_1;
		break;

	case rpc_cuDeviceGetCount:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudevicegetcount_1;
		break;

	case rpc_cuInit:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cuinit_1;
		break;

	case rpc_cuDriverGetVersion:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudrivergetversion_1;
		break;

	case rpc_cuDeviceGet:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudeviceget_1;
		break;

	case rpc_cuDeviceGetName:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_str_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudevicegetname_1;
		break;

	case rpc_cuDeviceTotalMem:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_u64_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudevicetotalmem_1;
		break;

	case rpc_cuDeviceGetAttribute:
		_xdr_argument = (xdrproc_t) xdr_rpc_cudevicegetattribute_1_argument;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudevicegetattribute_1;
		break;

	case rpc_cuDeviceGetUuid:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_uuid_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudevicegetuuid_1;
		break;

	case rpc_cuCtxGetCurrent:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cuctxgetcurrent_1;
		break;

	case rpc_cuCtxSetCurrent:
		_xdr_argument = (xdrproc_t) xdr_uint64_t;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cuctxsetcurrent_1;
		break;

	case rpc_cuDevicePrimaryCtxRetain:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudeviceprimaryctxretain_1;
		break;

	case rpc_cuModuleGetFunction:
		_xdr_argument = (xdrproc_t) xdr_rpc_cumodulegetfunction_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cumodulegetfunction_1;
		break;

	case rpc_cuGetExportTable:
		_xdr_argument = (xdrproc_t) xdr_rpc_uuid;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cugetexporttable_1;
		break;

	case rpc_cuMemAlloc:
		_xdr_argument = (xdrproc_t) xdr_uint64_t;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cumemalloc_1;
		break;

	case rpc_cuCtxGetDevice:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cuctxgetdevice_1;
		break;

	case rpc_cuMemcpyHtoD:
		_xdr_argument = (xdrproc_t) xdr_rpc_cumemcpyhtod_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cumemcpyhtod_1;
		break;

	case rpc_cuLaunchKernel:
		_xdr_argument = (xdrproc_t) xdr_rpc_culaunchkernel_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_culaunchkernel_1;
		break;

	case rpc_hidden_get_device_ctx:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_get_device_ctx_1;
		break;

	case rpc_hidden_get_module:
		_xdr_argument = (xdrproc_t) xdr_rpc_hidden_get_module_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_get_module_1;
		break;

	case rpc_hidden_1_1:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_1_1_1;
		break;

	case rpc_hidden_1_3:
		_xdr_argument = (xdrproc_t) xdr_rpc_hidden_1_3_1_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_1_3_1;
		break;

	case rpc_hidden_1_5:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_1_5_1;
		break;

	case rpc_hidden_2_1:
		_xdr_argument = (xdrproc_t) xdr_uint64_t;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_2_1_1;
		break;

	case rpc_hidden_3_0:
		_xdr_argument = (xdrproc_t) xdr_rpc_hidden_3_0_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_3_0_1;
		break;

	case rpc_hidden_3_2:
		_xdr_argument = (xdrproc_t) xdr_rpc_hidden_3_2_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_3_2_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!rpc_cd_prog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}
