/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cpu_rpc_prot.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_rpc_checkpoint_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_checkpoint_1_svc(result, rqstp));
}

int
_rpc_deinit_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_deinit_1_svc(result, rqstp));
}

int
_rpc_printmessage_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_printmessage_1_svc(*argp, result, rqstp));
}

int
_cuda_choose_device_1 (mem_data  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_choose_device_1_svc(*argp, result, rqstp));
}

int
_cuda_device_get_attribute_1 (cuda_device_get_attribute_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_get_attribute_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_device_get_by_pci_bus_id_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_get_by_pci_bus_id_1_svc(*argp, result, rqstp));
}

int
_cuda_device_get_cache_config_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_get_cache_config_1_svc(result, rqstp));
}

int
_cuda_device_get_limit_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_get_limit_1_svc(*argp, result, rqstp));
}

int
_cuda_device_get_p2p_attribute_1 (cuda_device_get_p2p_attribute_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_get_p2p_attribute_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_cuda_device_get_pci_bus_id_1 (cuda_device_get_pci_bus_id_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_get_pci_bus_id_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_device_get_shared_mem_config_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_get_shared_mem_config_1_svc(result, rqstp));
}

int
_cuda_device_get_stream_priority_range_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_get_stream_priority_range_1_svc(result, rqstp));
}

int
_cuda_device_get_texture_lmw_1 (cuda_device_get_texture_lmw_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_get_texture_lmw_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_device_reset_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_reset_1_svc(result, rqstp));
}

int
_cuda_device_set_cache_config_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_set_cache_config_1_svc(*argp, result, rqstp));
}

int
_cuda_device_set_limit_1 (cuda_device_set_limit_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_set_limit_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_device_set_shared_mem_config_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_set_shared_mem_config_1_svc(*argp, result, rqstp));
}

int
_cuda_device_synchronize_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_synchronize_1_svc(result, rqstp));
}

int
_cuda_get_device_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_get_device_1_svc(result, rqstp));
}

int
_cuda_get_device_count_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_get_device_count_1_svc(result, rqstp));
}

int
_cuda_get_device_flags_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_get_device_flags_1_svc(result, rqstp));
}

int
_cuda_get_device_properties_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_get_device_properties_1_svc(*argp, result, rqstp));
}

int
_cuda_set_device_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_set_device_1_svc(*argp, result, rqstp));
}

int
_cuda_set_device_flags_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_set_device_flags_1_svc(*argp, result, rqstp));
}

int
_cuda_set_valid_devices_1 (cuda_set_valid_devices_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_set_valid_devices_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_get_error_name_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_get_error_name_1_svc(*argp, result, rqstp));
}

int
_cuda_get_error_string_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_get_error_string_1_svc(*argp, result, rqstp));
}

int
_cuda_get_last_error_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_get_last_error_1_svc(result, rqstp));
}

int
_cuda_peek_at_last_error_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_peek_at_last_error_1_svc(result, rqstp));
}

int
_cuda_ctx_reset_persisting_l2cache_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_ctx_reset_persisting_l2cache_1_svc(result, rqstp));
}

int
_cuda_stream_copy_attributes_1 (cuda_stream_copy_attributes_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_stream_copy_attributes_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_stream_create_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_stream_create_1_svc(result, rqstp));
}

int
_cuda_stream_create_with_flags_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_stream_create_with_flags_1_svc(*argp, result, rqstp));
}

int
_cuda_stream_create_with_priority_1 (cuda_stream_create_with_priority_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_stream_create_with_priority_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_stream_destroy_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_stream_destroy_1_svc(*argp, result, rqstp));
}

int
_cuda_stream_get_flags_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_stream_get_flags_1_svc(*argp, result, rqstp));
}

int
_cuda_stream_get_priority_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_stream_get_priority_1_svc(*argp, result, rqstp));
}

int
_cuda_stream_query_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_stream_query_1_svc(*argp, result, rqstp));
}

int
_cuda_stream_synchronize_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_stream_synchronize_1_svc(*argp, result, rqstp));
}

int
_cuda_stream_wait_event_1 (cuda_stream_wait_event_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_stream_wait_event_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_cuda_thread_exchange_stream_capture_mode_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_thread_exchange_stream_capture_mode_1_svc(*argp, result, rqstp));
}

int
_cuda_event_create_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_event_create_1_svc(result, rqstp));
}

int
_cuda_event_create_with_flags_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_event_create_with_flags_1_svc(*argp, result, rqstp));
}

int
_cuda_event_destroy_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_event_destroy_1_svc(*argp, result, rqstp));
}

int
_cuda_event_elapsed_time_1 (cuda_event_elapsed_time_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_event_elapsed_time_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_event_query_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_event_query_1_svc(*argp, result, rqstp));
}

int
_cuda_event_record_1 (cuda_event_record_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_event_record_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_event_record_with_flags_1 (cuda_event_record_with_flags_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_event_record_with_flags_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_cuda_event_synchronize_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_event_synchronize_1_svc(*argp, result, rqstp));
}

int
_cuda_func_get_attributes_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_func_get_attributes_1_svc(*argp, result, rqstp));
}

int
_cuda_func_set_attributes_1 (cuda_func_set_attributes_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_func_set_attributes_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_cuda_func_set_cache_config_1 (cuda_func_set_cache_config_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_func_set_cache_config_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_func_set_shared_mem_config_1 (cuda_func_set_shared_mem_config_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_func_set_shared_mem_config_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_launch_cooperative_kernel_1 (cuda_launch_cooperative_kernel_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_launch_cooperative_kernel_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, argp->arg6, result, rqstp));
}

int
_cuda_launch_cooperative_kernel_multi_device_1 (cuda_launch_cooperative_kernel_multi_device_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_launch_cooperative_kernel_multi_device_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, argp->arg6, argp->arg7, argp->arg8, result, rqstp));
}

int
_cuda_launch_kernel_1 (cuda_launch_kernel_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_launch_kernel_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, argp->arg6, result, rqstp));
}

int
_cuda_occupancy_available_dsmpb_1 (cuda_occupancy_available_dsmpb_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_occupancy_available_dsmpb_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_cuda_occupancy_max_active_bpm_1 (cuda_occupancy_max_active_bpm_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_occupancy_max_active_bpm_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_cuda_occupancy_max_active_bpm_with_flags_1 (cuda_occupancy_max_active_bpm_with_flags_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_occupancy_max_active_bpm_with_flags_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, result, rqstp));
}

int
_cuda_array_get_info_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_array_get_info_1_svc(*argp, result, rqstp));
}

int
_cuda_array_get_sparse_properties_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_array_get_sparse_properties_1_svc(*argp, result, rqstp));
}

int
_cuda_free_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_free_1_svc(*argp, result, rqstp));
}

int
_cuda_free_array_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_free_array_1_svc(*argp, result, rqstp));
}

int
_cuda_free_host_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_free_host_1_svc(*argp, result, rqstp));
}

int
_cuda_get_symbol_address_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_get_symbol_address_1_svc(*argp, result, rqstp));
}

int
_cuda_get_symbol_size_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_get_symbol_size_1_svc(*argp, result, rqstp));
}

int
_cuda_host_alloc_1 (cuda_host_alloc_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_host_alloc_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, result, rqstp));
}

int
_cuda_host_get_device_pointer_1 (cuda_host_get_device_pointer_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_host_get_device_pointer_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_host_get_flags_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_host_get_flags_1_svc(*argp, result, rqstp));
}

int
_cuda_malloc_1 (size_t  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_malloc_1_svc(*argp, result, rqstp));
}

int
_cuda_malloc_3d_1 (cuda_malloc_3d_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_malloc_3d_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_cuda_malloc_3d_array_1 (cuda_malloc_3d_array_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_malloc_3d_array_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, result, rqstp));
}

int
_cuda_malloc_array_1 (cuda_malloc_array_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_malloc_array_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, result, rqstp));
}

int
_cuda_malloc_pitch_1 (cuda_malloc_pitch_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_malloc_pitch_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_mem_advise_1 (cuda_mem_advise_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_mem_advise_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, result, rqstp));
}

int
_cuda_mem_get_info_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_mem_get_info_1_svc(result, rqstp));
}

int
_cuda_mem_prefetch_async_1 (cuda_mem_prefetch_async_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_mem_prefetch_async_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, result, rqstp));
}

int
_cuda_memcpy_htod_1 (cuda_memcpy_htod_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_memcpy_htod_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_cuda_memcpy_dtoh_1 (cuda_memcpy_dtoh_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_memcpy_dtoh_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_memcpy_shm_1 (cuda_memcpy_shm_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_memcpy_shm_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, result, rqstp));
}

int
_cuda_memcpy_dtod_1 (cuda_memcpy_dtod_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_memcpy_dtod_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_cuda_memcpy_to_symbol_1 (cuda_memcpy_to_symbol_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_memcpy_to_symbol_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, result, rqstp));
}

int
_cuda_memcpy_to_symbol_shm_1 (cuda_memcpy_to_symbol_shm_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_memcpy_to_symbol_shm_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, result, rqstp));
}

int
_cuda_memcpy_ib_1 (cuda_memcpy_ib_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_memcpy_ib_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, result, rqstp));
}

int
_cuda_memset_1 (cuda_memset_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_memset_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_cuda_memset_2d_1 (cuda_memset_2d_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_memset_2d_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, result, rqstp));
}

int
_cuda_memset_3d_1 (cuda_memset_3d_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_memset_3d_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, argp->arg6, argp->arg7, argp->arg8, result, rqstp));
}

int
_cuda_device_can_access_peer_1 (cuda_device_can_access_peer_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_can_access_peer_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_device_disable_peer_access_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_disable_peer_access_1_svc(*argp, result, rqstp));
}

int
_cuda_device_enable_peer_access_1 (cuda_device_enable_peer_access_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_device_enable_peer_access_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_cuda_driver_get_version_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_driver_get_version_1_svc(result, rqstp));
}

int
_cuda_runtime_get_version_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (cuda_runtime_get_version_1_svc(result, rqstp));
}

int
_rpc_cudevicegetcount_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudevicegetcount_1_svc(result, rqstp));
}

int
_rpc_cuinit_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cuinit_1_svc(*argp, result, rqstp));
}

int
_rpc_cudrivergetversion_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudrivergetversion_1_svc(result, rqstp));
}

int
_rpc_cudeviceget_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudeviceget_1_svc(*argp, result, rqstp));
}

int
_rpc_cudevicegetname_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudevicegetname_1_svc(*argp, result, rqstp));
}

int
_rpc_cudevicetotalmem_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudevicetotalmem_1_svc(*argp, result, rqstp));
}

int
_rpc_cudevicegetattribute_1 (rpc_cudevicegetattribute_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudevicegetattribute_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_rpc_cudevicegetuuid_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudevicegetuuid_1_svc(*argp, result, rqstp));
}

int
_rpc_cuctxgetcurrent_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cuctxgetcurrent_1_svc(result, rqstp));
}

int
_rpc_cuctxsetcurrent_1 (uint64_t  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cuctxsetcurrent_1_svc(*argp, result, rqstp));
}

int
_rpc_cudeviceprimaryctxretain_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cudeviceprimaryctxretain_1_svc(*argp, result, rqstp));
}

int
_rpc_cumodulegetfunction_1 (rpc_cumodulegetfunction_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cumodulegetfunction_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_rpc_cugetexporttable_1 (rpc_uuid  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cugetexporttable_1_svc(*argp, result, rqstp));
}

int
_rpc_cumemalloc_1 (uint64_t  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cumemalloc_1_svc(*argp, result, rqstp));
}

int
_rpc_cuctxgetdevice_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cuctxgetdevice_1_svc(result, rqstp));
}

int
_rpc_cumemcpyhtod_1 (rpc_cumemcpyhtod_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cumemcpyhtod_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_rpc_culaunchkernel_1 (rpc_culaunchkernel_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_culaunchkernel_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, argp->arg6, argp->arg7, argp->arg8, argp->arg9, argp->arg10, result, rqstp));
}

int
_rpc_hidden_get_device_ctx_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_get_device_ctx_1_svc(*argp, result, rqstp));
}

int
_rpc_hidden_get_module_1 (rpc_hidden_get_module_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_get_module_1_svc(argp->arg2, argp->arg3, argp->arg4, argp->arg5, result, rqstp));
}

int
_rpc_hidden_1_1_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_1_1_1_svc(result, rqstp));
}

int
_rpc_hidden_1_3_1 (rpc_hidden_1_3_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_1_3_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_rpc_hidden_1_5_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_1_5_1_svc(result, rqstp));
}

int
_rpc_hidden_2_1_1 (uint64_t  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_2_1_1_svc(*argp, result, rqstp));
}

int
_rpc_hidden_3_0_1 (rpc_hidden_3_0_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_3_0_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_rpc_hidden_3_2_1 (rpc_hidden_3_2_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_hidden_3_2_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_rpc_cusolverdncreate_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cusolverdncreate_1_svc(result, rqstp));
}

int
_rpc_cusolverdnsetstream_1 (rpc_cusolverdnsetstream_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cusolverdnsetstream_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_rpc_cusolverdndgetrf_buffersize_1 (rpc_cusolverdndgetrf_buffersize_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cusolverdndgetrf_buffersize_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, result, rqstp));
}

int
_rpc_cusolverdndgetrf_1 (rpc_cusolverdndgetrf_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cusolverdndgetrf_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, argp->arg6, argp->arg7, argp->arg8, result, rqstp));
}

int
_rpc_cusolverdndgetrs_1 (rpc_cusolverdndgetrs_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cusolverdndgetrs_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, argp->arg5, argp->arg6, argp->arg7, argp->arg8, argp->arg9, argp->arg10, result, rqstp));
}

int
_rpc_cusolverdndestroy_1 (ptr  *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_cusolverdndestroy_1_svc(*argp, result, rqstp));
}

void
rpc_cd_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *rpc_printmessage_1_arg;
		mem_data cuda_choose_device_1_arg;
		cuda_device_get_attribute_1_argument cuda_device_get_attribute_1_arg;
		char *cuda_device_get_by_pci_bus_id_1_arg;
		int cuda_device_get_limit_1_arg;
		cuda_device_get_p2p_attribute_1_argument cuda_device_get_p2p_attribute_1_arg;
		cuda_device_get_pci_bus_id_1_argument cuda_device_get_pci_bus_id_1_arg;
		cuda_device_get_texture_lmw_1_argument cuda_device_get_texture_lmw_1_arg;
		int cuda_device_set_cache_config_1_arg;
		cuda_device_set_limit_1_argument cuda_device_set_limit_1_arg;
		int cuda_device_set_shared_mem_config_1_arg;
		int cuda_get_device_properties_1_arg;
		int cuda_set_device_1_arg;
		int cuda_set_device_flags_1_arg;
		cuda_set_valid_devices_1_argument cuda_set_valid_devices_1_arg;
		int cuda_get_error_name_1_arg;
		int cuda_get_error_string_1_arg;
		cuda_stream_copy_attributes_1_argument cuda_stream_copy_attributes_1_arg;
		int cuda_stream_create_with_flags_1_arg;
		cuda_stream_create_with_priority_1_argument cuda_stream_create_with_priority_1_arg;
		ptr cuda_stream_destroy_1_arg;
		ptr cuda_stream_get_flags_1_arg;
		ptr cuda_stream_get_priority_1_arg;
		ptr cuda_stream_query_1_arg;
		ptr cuda_stream_synchronize_1_arg;
		cuda_stream_wait_event_1_argument cuda_stream_wait_event_1_arg;
		int cuda_thread_exchange_stream_capture_mode_1_arg;
		int cuda_event_create_with_flags_1_arg;
		ptr cuda_event_destroy_1_arg;
		cuda_event_elapsed_time_1_argument cuda_event_elapsed_time_1_arg;
		ptr cuda_event_query_1_arg;
		cuda_event_record_1_argument cuda_event_record_1_arg;
		cuda_event_record_with_flags_1_argument cuda_event_record_with_flags_1_arg;
		ptr cuda_event_synchronize_1_arg;
		ptr cuda_func_get_attributes_1_arg;
		cuda_func_set_attributes_1_argument cuda_func_set_attributes_1_arg;
		cuda_func_set_cache_config_1_argument cuda_func_set_cache_config_1_arg;
		cuda_func_set_shared_mem_config_1_argument cuda_func_set_shared_mem_config_1_arg;
		cuda_launch_cooperative_kernel_1_argument cuda_launch_cooperative_kernel_1_arg;
		cuda_launch_cooperative_kernel_multi_device_1_argument cuda_launch_cooperative_kernel_multi_device_1_arg;
		cuda_launch_kernel_1_argument cuda_launch_kernel_1_arg;
		cuda_occupancy_available_dsmpb_1_argument cuda_occupancy_available_dsmpb_1_arg;
		cuda_occupancy_max_active_bpm_1_argument cuda_occupancy_max_active_bpm_1_arg;
		cuda_occupancy_max_active_bpm_with_flags_1_argument cuda_occupancy_max_active_bpm_with_flags_1_arg;
		ptr cuda_array_get_info_1_arg;
		ptr cuda_array_get_sparse_properties_1_arg;
		ptr cuda_free_1_arg;
		ptr cuda_free_array_1_arg;
		int cuda_free_host_1_arg;
		ptr cuda_get_symbol_address_1_arg;
		ptr cuda_get_symbol_size_1_arg;
		cuda_host_alloc_1_argument cuda_host_alloc_1_arg;
		cuda_host_get_device_pointer_1_argument cuda_host_get_device_pointer_1_arg;
		ptr cuda_host_get_flags_1_arg;
		size_t cuda_malloc_1_arg;
		cuda_malloc_3d_1_argument cuda_malloc_3d_1_arg;
		cuda_malloc_3d_array_1_argument cuda_malloc_3d_array_1_arg;
		cuda_malloc_array_1_argument cuda_malloc_array_1_arg;
		cuda_malloc_pitch_1_argument cuda_malloc_pitch_1_arg;
		cuda_mem_advise_1_argument cuda_mem_advise_1_arg;
		cuda_mem_prefetch_async_1_argument cuda_mem_prefetch_async_1_arg;
		cuda_memcpy_htod_1_argument cuda_memcpy_htod_1_arg;
		cuda_memcpy_dtoh_1_argument cuda_memcpy_dtoh_1_arg;
		cuda_memcpy_shm_1_argument cuda_memcpy_shm_1_arg;
		cuda_memcpy_dtod_1_argument cuda_memcpy_dtod_1_arg;
		cuda_memcpy_to_symbol_1_argument cuda_memcpy_to_symbol_1_arg;
		cuda_memcpy_to_symbol_shm_1_argument cuda_memcpy_to_symbol_shm_1_arg;
		cuda_memcpy_ib_1_argument cuda_memcpy_ib_1_arg;
		cuda_memset_1_argument cuda_memset_1_arg;
		cuda_memset_2d_1_argument cuda_memset_2d_1_arg;
		cuda_memset_3d_1_argument cuda_memset_3d_1_arg;
		cuda_device_can_access_peer_1_argument cuda_device_can_access_peer_1_arg;
		int cuda_device_disable_peer_access_1_arg;
		cuda_device_enable_peer_access_1_argument cuda_device_enable_peer_access_1_arg;
		int rpc_cuinit_1_arg;
		int rpc_cudeviceget_1_arg;
		int rpc_cudevicegetname_1_arg;
		int rpc_cudevicetotalmem_1_arg;
		rpc_cudevicegetattribute_1_argument rpc_cudevicegetattribute_1_arg;
		int rpc_cudevicegetuuid_1_arg;
		uint64_t rpc_cuctxsetcurrent_1_arg;
		int rpc_cudeviceprimaryctxretain_1_arg;
		rpc_cumodulegetfunction_1_argument rpc_cumodulegetfunction_1_arg;
		rpc_uuid rpc_cugetexporttable_1_arg;
		uint64_t rpc_cumemalloc_1_arg;
		rpc_cumemcpyhtod_1_argument rpc_cumemcpyhtod_1_arg;
		rpc_culaunchkernel_1_argument rpc_culaunchkernel_1_arg;
		int rpc_hidden_get_device_ctx_1_arg;
		rpc_hidden_get_module_1_argument rpc_hidden_get_module_1_arg;
		rpc_hidden_1_3_1_argument rpc_hidden_1_3_1_arg;
		uint64_t rpc_hidden_2_1_1_arg;
		rpc_hidden_3_0_1_argument rpc_hidden_3_0_1_arg;
		rpc_hidden_3_2_1_argument rpc_hidden_3_2_1_arg;
		rpc_cusolverdnsetstream_1_argument rpc_cusolverdnsetstream_1_arg;
		rpc_cusolverdndgetrf_buffersize_1_argument rpc_cusolverdndgetrf_buffersize_1_arg;
		rpc_cusolverdndgetrf_1_argument rpc_cusolverdndgetrf_1_arg;
		rpc_cusolverdndgetrs_1_argument rpc_cusolverdndgetrs_1_arg;
		ptr rpc_cusolverdndestroy_1_arg;
	} argument;
	union {
		int rpc_checkpoint_1_res;
		int rpc_deinit_1_res;
		int rpc_printmessage_1_res;
		int_result cuda_choose_device_1_res;
		int_result cuda_device_get_attribute_1_res;
		int_result cuda_device_get_by_pci_bus_id_1_res;
		int_result cuda_device_get_cache_config_1_res;
		u64_result cuda_device_get_limit_1_res;
		int_result cuda_device_get_p2p_attribute_1_res;
		str_result cuda_device_get_pci_bus_id_1_res;
		int_result cuda_device_get_shared_mem_config_1_res;
		dint_result cuda_device_get_stream_priority_range_1_res;
		u64_result cuda_device_get_texture_lmw_1_res;
		int cuda_device_reset_1_res;
		int cuda_device_set_cache_config_1_res;
		int cuda_device_set_limit_1_res;
		int cuda_device_set_shared_mem_config_1_res;
		int cuda_device_synchronize_1_res;
		int_result cuda_get_device_1_res;
		int_result cuda_get_device_count_1_res;
		int_result cuda_get_device_flags_1_res;
		mem_result cuda_get_device_properties_1_res;
		int cuda_set_device_1_res;
		int cuda_set_device_flags_1_res;
		int cuda_set_valid_devices_1_res;
		str_result cuda_get_error_name_1_res;
		str_result cuda_get_error_string_1_res;
		int cuda_get_last_error_1_res;
		int cuda_peek_at_last_error_1_res;
		int cuda_ctx_reset_persisting_l2cache_1_res;
		int cuda_stream_copy_attributes_1_res;
		ptr_result cuda_stream_create_1_res;
		ptr_result cuda_stream_create_with_flags_1_res;
		ptr_result cuda_stream_create_with_priority_1_res;
		int cuda_stream_destroy_1_res;
		int_result cuda_stream_get_flags_1_res;
		int_result cuda_stream_get_priority_1_res;
		int cuda_stream_query_1_res;
		int cuda_stream_synchronize_1_res;
		int cuda_stream_wait_event_1_res;
		int_result cuda_thread_exchange_stream_capture_mode_1_res;
		ptr_result cuda_event_create_1_res;
		ptr_result cuda_event_create_with_flags_1_res;
		int cuda_event_destroy_1_res;
		float_result cuda_event_elapsed_time_1_res;
		int cuda_event_query_1_res;
		int cuda_event_record_1_res;
		int cuda_event_record_with_flags_1_res;
		int cuda_event_synchronize_1_res;
		mem_result cuda_func_get_attributes_1_res;
		int cuda_func_set_attributes_1_res;
		int cuda_func_set_cache_config_1_res;
		int cuda_func_set_shared_mem_config_1_res;
		int cuda_launch_cooperative_kernel_1_res;
		int cuda_launch_cooperative_kernel_multi_device_1_res;
		int cuda_launch_kernel_1_res;
		u64_result cuda_occupancy_available_dsmpb_1_res;
		int_result cuda_occupancy_max_active_bpm_1_res;
		int_result cuda_occupancy_max_active_bpm_with_flags_1_res;
		mem_result cuda_array_get_info_1_res;
		mem_result cuda_array_get_sparse_properties_1_res;
		int cuda_free_1_res;
		int cuda_free_array_1_res;
		int cuda_free_host_1_res;
		ptr_result cuda_get_symbol_address_1_res;
		u64_result cuda_get_symbol_size_1_res;
		int cuda_host_alloc_1_res;
		ptr_result cuda_host_get_device_pointer_1_res;
		int_result cuda_host_get_flags_1_res;
		ptr_result cuda_malloc_1_res;
		pptr_result cuda_malloc_3d_1_res;
		ptr_result cuda_malloc_3d_array_1_res;
		ptr_result cuda_malloc_array_1_res;
		ptrsz_result cuda_malloc_pitch_1_res;
		int cuda_mem_advise_1_res;
		dsz_result cuda_mem_get_info_1_res;
		int cuda_mem_prefetch_async_1_res;
		int cuda_memcpy_htod_1_res;
		mem_result cuda_memcpy_dtoh_1_res;
		int cuda_memcpy_shm_1_res;
		int cuda_memcpy_dtod_1_res;
		int cuda_memcpy_to_symbol_1_res;
		int cuda_memcpy_to_symbol_shm_1_res;
		int cuda_memcpy_ib_1_res;
		int cuda_memset_1_res;
		int cuda_memset_2d_1_res;
		int cuda_memset_3d_1_res;
		int_result cuda_device_can_access_peer_1_res;
		int cuda_device_disable_peer_access_1_res;
		int cuda_device_enable_peer_access_1_res;
		int_result cuda_driver_get_version_1_res;
		int_result cuda_runtime_get_version_1_res;
		int_result rpc_cudevicegetcount_1_res;
		int rpc_cuinit_1_res;
		int_result rpc_cudrivergetversion_1_res;
		int_result rpc_cudeviceget_1_res;
		str_result rpc_cudevicegetname_1_res;
		u64_result rpc_cudevicetotalmem_1_res;
		int_result rpc_cudevicegetattribute_1_res;
		uuid_result rpc_cudevicegetuuid_1_res;
		ptr_result rpc_cuctxgetcurrent_1_res;
		int rpc_cuctxsetcurrent_1_res;
		ptr_result rpc_cudeviceprimaryctxretain_1_res;
		ptr_result rpc_cumodulegetfunction_1_res;
		ptr_result rpc_cugetexporttable_1_res;
		ptr_result rpc_cumemalloc_1_res;
		int_result rpc_cuctxgetdevice_1_res;
		int rpc_cumemcpyhtod_1_res;
		int rpc_culaunchkernel_1_res;
		ptr_result rpc_hidden_get_device_ctx_1_res;
		ptr_result rpc_hidden_get_module_1_res;
		ptr_result rpc_hidden_1_1_1_res;
		ptr_result rpc_hidden_1_5_1_res;
		int rpc_hidden_3_0_1_res;
		mem_result rpc_hidden_3_2_1_res;
		ptr_result rpc_cusolverdncreate_1_res;
		int rpc_cusolverdnsetstream_1_res;
		int_result rpc_cusolverdndgetrf_buffersize_1_res;
		int rpc_cusolverdndgetrf_1_res;
		int rpc_cusolverdndgetrs_1_res;
		int rpc_cusolverdndestroy_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case rpc_checkpoint:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_checkpoint_1;
		break;

	case rpc_deinit:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_deinit_1;
		break;

	case rpc_printmessage:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_printmessage_1;
		break;

	case CUDA_CHOOSE_DEVICE:
		_xdr_argument = (xdrproc_t) xdr_mem_data;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_choose_device_1;
		break;

	case CUDA_DEVICE_GET_ATTRIBUTE:
		_xdr_argument = (xdrproc_t) xdr_cuda_device_get_attribute_1_argument;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_attribute_1;
		break;

	case CUDA_DEVICE_GET_BY_PCI_BUS_ID:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_by_pci_bus_id_1;
		break;

	case CUDA_DEVICE_GET_CACHE_CONFIG:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_cache_config_1;
		break;

	case CUDA_DEVICE_GET_LIMIT:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_u64_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_limit_1;
		break;

	case CUDA_DEVICE_GET_P2P_ATTRIBUTE:
		_xdr_argument = (xdrproc_t) xdr_cuda_device_get_p2p_attribute_1_argument;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_p2p_attribute_1;
		break;

	case CUDA_DEVICE_GET_PCI_BUS_ID:
		_xdr_argument = (xdrproc_t) xdr_cuda_device_get_pci_bus_id_1_argument;
		_xdr_result = (xdrproc_t) xdr_str_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_pci_bus_id_1;
		break;

	case CUDA_DEVICE_GET_SHARED_MEM_CONFIG:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_shared_mem_config_1;
		break;

	case CUDA_DEVICE_GET_STREAM_PRIORITY_RANGE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_dint_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_stream_priority_range_1;
		break;

	case CUDA_DEVICE_GET_TEXTURE_LMW:
		_xdr_argument = (xdrproc_t) xdr_cuda_device_get_texture_lmw_1_argument;
		_xdr_result = (xdrproc_t) xdr_u64_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_texture_lmw_1;
		break;

	case CUDA_DEVICE_RESET:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_reset_1;
		break;

	case CUDA_DEVICE_SET_CACHE_CONFIG:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_set_cache_config_1;
		break;

	case CUDA_DEVICE_SET_LIMIT:
		_xdr_argument = (xdrproc_t) xdr_cuda_device_set_limit_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_set_limit_1;
		break;

	case CUDA_DEVICE_SET_SHARED_MEM_CONFIG:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_set_shared_mem_config_1;
		break;

	case CUDA_DEVICE_SYNCHRONIZE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_synchronize_1;
		break;

	case CUDA_GET_DEVICE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_device_1;
		break;

	case CUDA_GET_DEVICE_COUNT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_device_count_1;
		break;

	case CUDA_GET_DEVICE_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_device_flags_1;
		break;

	case CUDA_GET_DEVICE_PROPERTIES:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_mem_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_device_properties_1;
		break;

	case CUDA_SET_DEVICE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_set_device_1;
		break;

	case CUDA_SET_DEVICE_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_set_device_flags_1;
		break;

	case CUDA_SET_VALID_DEVICES:
		_xdr_argument = (xdrproc_t) xdr_cuda_set_valid_devices_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_set_valid_devices_1;
		break;

	case CUDA_GET_ERROR_NAME:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_str_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_error_name_1;
		break;

	case CUDA_GET_ERROR_STRING:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_str_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_error_string_1;
		break;

	case CUDA_GET_LAST_ERROR:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_last_error_1;
		break;

	case CUDA_PEEK_AT_LAST_ERROR:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_peek_at_last_error_1;
		break;

	case CUDA_CTX_RESET_PERSISTING_L2CACHE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_ctx_reset_persisting_l2cache_1;
		break;

	case CUDA_STREAM_COPY_ATTRIBUTES:
		_xdr_argument = (xdrproc_t) xdr_cuda_stream_copy_attributes_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_copy_attributes_1;
		break;

	case CUDA_STREAM_CREATE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_create_1;
		break;

	case CUDA_STREAM_CREATE_WITH_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_create_with_flags_1;
		break;

	case CUDA_STREAM_CREATE_WITH_PRIORITY:
		_xdr_argument = (xdrproc_t) xdr_cuda_stream_create_with_priority_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_create_with_priority_1;
		break;

	case CUDA_STREAM_DESTROY:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_destroy_1;
		break;

	case CUDA_STREAM_GET_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_get_flags_1;
		break;

	case CUDA_STREAM_GET_PRIORITY:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_get_priority_1;
		break;

	case CUDA_STREAM_QUERY:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_query_1;
		break;

	case CUDA_STREAM_SYNCHRONIZE:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_synchronize_1;
		break;

	case CUDA_STREAM_WAIT_EVENT:
		_xdr_argument = (xdrproc_t) xdr_cuda_stream_wait_event_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_wait_event_1;
		break;

	case CUDA_THREAD_EXCHANGE_STREAM_CAPTURE_MODE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_thread_exchange_stream_capture_mode_1;
		break;

	case CUDA_EVENT_CREATE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_create_1;
		break;

	case CUDA_EVENT_CREATE_WITH_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_create_with_flags_1;
		break;

	case CUDA_EVENT_DESTROY:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_destroy_1;
		break;

	case CUDA_EVENT_ELAPSED_TIME:
		_xdr_argument = (xdrproc_t) xdr_cuda_event_elapsed_time_1_argument;
		_xdr_result = (xdrproc_t) xdr_float_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_elapsed_time_1;
		break;

	case CUDA_EVENT_QUERY:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_query_1;
		break;

	case CUDA_EVENT_RECORD:
		_xdr_argument = (xdrproc_t) xdr_cuda_event_record_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_record_1;
		break;

	case CUDA_EVENT_RECORD_WITH_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_cuda_event_record_with_flags_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_record_with_flags_1;
		break;

	case CUDA_EVENT_SYNCHRONIZE:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_synchronize_1;
		break;

	case CUDA_FUNC_GET_ATTRIBUTES:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_mem_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_func_get_attributes_1;
		break;

	case CUDA_FUNC_SET_ATTRIBUTES:
		_xdr_argument = (xdrproc_t) xdr_cuda_func_set_attributes_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_func_set_attributes_1;
		break;

	case CUDA_FUNC_SET_CACHE_CONFIG:
		_xdr_argument = (xdrproc_t) xdr_cuda_func_set_cache_config_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_func_set_cache_config_1;
		break;

	case CUDA_FUNC_SET_SHARED_MEM_CONFIG:
		_xdr_argument = (xdrproc_t) xdr_cuda_func_set_shared_mem_config_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_func_set_shared_mem_config_1;
		break;

	case CUDA_LAUNCH_COOPERATIVE_KERNEL:
		_xdr_argument = (xdrproc_t) xdr_cuda_launch_cooperative_kernel_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_launch_cooperative_kernel_1;
		break;

	case CUDA_LAUNCH_COOPERATIVE_KERNEL_MULTI_DEVICE:
		_xdr_argument = (xdrproc_t) xdr_cuda_launch_cooperative_kernel_multi_device_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_launch_cooperative_kernel_multi_device_1;
		break;

	case CUDA_LAUNCH_KERNEL:
		_xdr_argument = (xdrproc_t) xdr_cuda_launch_kernel_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_launch_kernel_1;
		break;

	case CUDA_OCCUPANCY_AVAILABLE_DSMPB:
		_xdr_argument = (xdrproc_t) xdr_cuda_occupancy_available_dsmpb_1_argument;
		_xdr_result = (xdrproc_t) xdr_u64_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_occupancy_available_dsmpb_1;
		break;

	case CUDA_OCCUPANCY_MAX_ACTIVE_BPM:
		_xdr_argument = (xdrproc_t) xdr_cuda_occupancy_max_active_bpm_1_argument;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_occupancy_max_active_bpm_1;
		break;

	case CUDA_OCCUPANCY_MAX_ACTIVE_BPM_WITH_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_cuda_occupancy_max_active_bpm_with_flags_1_argument;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_occupancy_max_active_bpm_with_flags_1;
		break;

	case CUDA_ARRAY_GET_INFO:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_mem_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_array_get_info_1;
		break;

	case CUDA_ARRAY_GET_SPARSE_PROPERTIES:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_mem_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_array_get_sparse_properties_1;
		break;

	case CUDA_FREE:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_free_1;
		break;

	case CUDA_FREE_ARRAY:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_free_array_1;
		break;

	case CUDA_FREE_HOST:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_free_host_1;
		break;

	case CUDA_GET_SYMBOL_ADDRESS:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_symbol_address_1;
		break;

	case CUDA_GET_SYMBOL_SIZE:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_u64_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_symbol_size_1;
		break;

	case CUDA_HOST_ALLOC:
		_xdr_argument = (xdrproc_t) xdr_cuda_host_alloc_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_host_alloc_1;
		break;

	case CUDA_HOST_GET_DEVICE_POINTER:
		_xdr_argument = (xdrproc_t) xdr_cuda_host_get_device_pointer_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_host_get_device_pointer_1;
		break;

	case CUDA_HOST_GET_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_host_get_flags_1;
		break;

	case CUDA_MALLOC:
		_xdr_argument = (xdrproc_t) xdr_size_t;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_malloc_1;
		break;

	case CUDA_MALLOC_3D:
		_xdr_argument = (xdrproc_t) xdr_cuda_malloc_3d_1_argument;
		_xdr_result = (xdrproc_t) xdr_pptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_malloc_3d_1;
		break;

	case CUDA_MALLOC_3D_ARRAY:
		_xdr_argument = (xdrproc_t) xdr_cuda_malloc_3d_array_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_malloc_3d_array_1;
		break;

	case CUDA_MALLOC_ARRAY:
		_xdr_argument = (xdrproc_t) xdr_cuda_malloc_array_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_malloc_array_1;
		break;

	case CUDA_MALLOC_PITCH:
		_xdr_argument = (xdrproc_t) xdr_cuda_malloc_pitch_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptrsz_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_malloc_pitch_1;
		break;

	case CUDA_MEM_ADVISE:
		_xdr_argument = (xdrproc_t) xdr_cuda_mem_advise_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_mem_advise_1;
		break;

	case CUDA_MEM_GET_INFO:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_dsz_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_mem_get_info_1;
		break;

	case CUDA_MEM_PREFETCH_ASYNC:
		_xdr_argument = (xdrproc_t) xdr_cuda_mem_prefetch_async_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_mem_prefetch_async_1;
		break;

	case CUDA_MEMCPY_HTOD:
		_xdr_argument = (xdrproc_t) xdr_cuda_memcpy_htod_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memcpy_htod_1;
		break;

	case CUDA_MEMCPY_DTOH:
		_xdr_argument = (xdrproc_t) xdr_cuda_memcpy_dtoh_1_argument;
		_xdr_result = (xdrproc_t) xdr_mem_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memcpy_dtoh_1;
		break;

	case CUDA_MEMCPY_SHM:
		_xdr_argument = (xdrproc_t) xdr_cuda_memcpy_shm_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memcpy_shm_1;
		break;

	case CUDA_MEMCPY_DTOD:
		_xdr_argument = (xdrproc_t) xdr_cuda_memcpy_dtod_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memcpy_dtod_1;
		break;

	case CUDA_MEMCPY_TO_SYMBOL:
		_xdr_argument = (xdrproc_t) xdr_cuda_memcpy_to_symbol_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memcpy_to_symbol_1;
		break;

	case CUDA_MEMCPY_TO_SYMBOL_SHM:
		_xdr_argument = (xdrproc_t) xdr_cuda_memcpy_to_symbol_shm_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memcpy_to_symbol_shm_1;
		break;

	case CUDA_MEMCPY_IB:
		_xdr_argument = (xdrproc_t) xdr_cuda_memcpy_ib_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memcpy_ib_1;
		break;

	case CUDA_MEMSET:
		_xdr_argument = (xdrproc_t) xdr_cuda_memset_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memset_1;
		break;

	case CUDA_MEMSET_2D:
		_xdr_argument = (xdrproc_t) xdr_cuda_memset_2d_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memset_2d_1;
		break;

	case CUDA_MEMSET_3D:
		_xdr_argument = (xdrproc_t) xdr_cuda_memset_3d_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memset_3d_1;
		break;

	case CUDA_DEVICE_CAN_ACCESS_PEER:
		_xdr_argument = (xdrproc_t) xdr_cuda_device_can_access_peer_1_argument;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_can_access_peer_1;
		break;

	case CUDA_DEVICE_DISABLE_PEER_ACCESS:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_disable_peer_access_1;
		break;

	case CUDA_DEVICE_ENABLE_PEER_ACCESS:
		_xdr_argument = (xdrproc_t) xdr_cuda_device_enable_peer_access_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_enable_peer_access_1;
		break;

	case CUDA_DRIVER_GET_VERSION:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_driver_get_version_1;
		break;

	case CUDA_RUNTIME_GET_VERSION:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_runtime_get_version_1;
		break;

	case rpc_cuDeviceGetCount:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudevicegetcount_1;
		break;

	case rpc_cuInit:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cuinit_1;
		break;

	case rpc_cuDriverGetVersion:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudrivergetversion_1;
		break;

	case rpc_cuDeviceGet:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudeviceget_1;
		break;

	case rpc_cuDeviceGetName:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_str_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudevicegetname_1;
		break;

	case rpc_cuDeviceTotalMem:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_u64_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudevicetotalmem_1;
		break;

	case rpc_cuDeviceGetAttribute:
		_xdr_argument = (xdrproc_t) xdr_rpc_cudevicegetattribute_1_argument;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudevicegetattribute_1;
		break;

	case rpc_cuDeviceGetUuid:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_uuid_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudevicegetuuid_1;
		break;

	case rpc_cuCtxGetCurrent:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cuctxgetcurrent_1;
		break;

	case rpc_cuCtxSetCurrent:
		_xdr_argument = (xdrproc_t) xdr_uint64_t;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cuctxsetcurrent_1;
		break;

	case rpc_cuDevicePrimaryCtxRetain:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudeviceprimaryctxretain_1;
		break;

	case rpc_cuModuleGetFunction:
		_xdr_argument = (xdrproc_t) xdr_rpc_cumodulegetfunction_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cumodulegetfunction_1;
		break;

	case rpc_cuGetExportTable:
		_xdr_argument = (xdrproc_t) xdr_rpc_uuid;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cugetexporttable_1;
		break;

	case rpc_cuMemAlloc:
		_xdr_argument = (xdrproc_t) xdr_uint64_t;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cumemalloc_1;
		break;

	case rpc_cuCtxGetDevice:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cuctxgetdevice_1;
		break;

	case rpc_cuMemcpyHtoD:
		_xdr_argument = (xdrproc_t) xdr_rpc_cumemcpyhtod_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cumemcpyhtod_1;
		break;

	case rpc_cuLaunchKernel:
		_xdr_argument = (xdrproc_t) xdr_rpc_culaunchkernel_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_culaunchkernel_1;
		break;

	case rpc_hidden_get_device_ctx:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_get_device_ctx_1;
		break;

	case rpc_hidden_get_module:
		_xdr_argument = (xdrproc_t) xdr_rpc_hidden_get_module_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_get_module_1;
		break;

	case rpc_hidden_1_1:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_1_1_1;
		break;

	case rpc_hidden_1_3:
		_xdr_argument = (xdrproc_t) xdr_rpc_hidden_1_3_1_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_1_3_1;
		break;

	case rpc_hidden_1_5:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_1_5_1;
		break;

	case rpc_hidden_2_1:
		_xdr_argument = (xdrproc_t) xdr_uint64_t;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_2_1_1;
		break;

	case rpc_hidden_3_0:
		_xdr_argument = (xdrproc_t) xdr_rpc_hidden_3_0_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_3_0_1;
		break;

	case rpc_hidden_3_2:
		_xdr_argument = (xdrproc_t) xdr_rpc_hidden_3_2_1_argument;
		_xdr_result = (xdrproc_t) xdr_mem_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_3_2_1;
		break;

	case rpc_cusolverDnCreate:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cusolverdncreate_1;
		break;

	case rpc_cusolverDnSetStream:
		_xdr_argument = (xdrproc_t) xdr_rpc_cusolverdnsetstream_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cusolverdnsetstream_1;
		break;

	case rpc_cusolverDnDgetrf_bufferSize:
		_xdr_argument = (xdrproc_t) xdr_rpc_cusolverdndgetrf_buffersize_1_argument;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cusolverdndgetrf_buffersize_1;
		break;

	case rpc_cusolverDnDgetrf:
		_xdr_argument = (xdrproc_t) xdr_rpc_cusolverdndgetrf_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cusolverdndgetrf_1;
		break;

	case rpc_cusolverDnDgetrs:
		_xdr_argument = (xdrproc_t) xdr_rpc_cusolverdndgetrs_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cusolverdndgetrs_1;
		break;

	case rpc_cusolverDnDestroy:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cusolverdndestroy_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!rpc_cd_prog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}
void rpc_dispatch(struct svc_req *rqstp, xdrproc_t *ret_arg, xdrproc_t *ret_res, size_t *res_sz, bool_t (**ret_fun)(char *, void *, struct svc_req *))
{
	union {
		char *rpc_printmessage_1_arg;
		mem_data cuda_choose_device_1_arg;
		cuda_device_get_attribute_1_argument cuda_device_get_attribute_1_arg;
		char *cuda_device_get_by_pci_bus_id_1_arg;
		int cuda_device_get_limit_1_arg;
		cuda_device_get_p2p_attribute_1_argument cuda_device_get_p2p_attribute_1_arg;
		cuda_device_get_pci_bus_id_1_argument cuda_device_get_pci_bus_id_1_arg;
		cuda_device_get_texture_lmw_1_argument cuda_device_get_texture_lmw_1_arg;
		int cuda_device_set_cache_config_1_arg;
		cuda_device_set_limit_1_argument cuda_device_set_limit_1_arg;
		int cuda_device_set_shared_mem_config_1_arg;
		int cuda_get_device_properties_1_arg;
		int cuda_set_device_1_arg;
		int cuda_set_device_flags_1_arg;
		cuda_set_valid_devices_1_argument cuda_set_valid_devices_1_arg;
		int cuda_get_error_name_1_arg;
		int cuda_get_error_string_1_arg;
		cuda_stream_copy_attributes_1_argument cuda_stream_copy_attributes_1_arg;
		int cuda_stream_create_with_flags_1_arg;
		cuda_stream_create_with_priority_1_argument cuda_stream_create_with_priority_1_arg;
		ptr cuda_stream_destroy_1_arg;
		ptr cuda_stream_get_flags_1_arg;
		ptr cuda_stream_get_priority_1_arg;
		ptr cuda_stream_query_1_arg;
		ptr cuda_stream_synchronize_1_arg;
		cuda_stream_wait_event_1_argument cuda_stream_wait_event_1_arg;
		int cuda_thread_exchange_stream_capture_mode_1_arg;
		int cuda_event_create_with_flags_1_arg;
		ptr cuda_event_destroy_1_arg;
		cuda_event_elapsed_time_1_argument cuda_event_elapsed_time_1_arg;
		ptr cuda_event_query_1_arg;
		cuda_event_record_1_argument cuda_event_record_1_arg;
		cuda_event_record_with_flags_1_argument cuda_event_record_with_flags_1_arg;
		ptr cuda_event_synchronize_1_arg;
		ptr cuda_func_get_attributes_1_arg;
		cuda_func_set_attributes_1_argument cuda_func_set_attributes_1_arg;
		cuda_func_set_cache_config_1_argument cuda_func_set_cache_config_1_arg;
		cuda_func_set_shared_mem_config_1_argument cuda_func_set_shared_mem_config_1_arg;
		cuda_launch_cooperative_kernel_1_argument cuda_launch_cooperative_kernel_1_arg;
		cuda_launch_cooperative_kernel_multi_device_1_argument cuda_launch_cooperative_kernel_multi_device_1_arg;
		cuda_launch_kernel_1_argument cuda_launch_kernel_1_arg;
		cuda_occupancy_available_dsmpb_1_argument cuda_occupancy_available_dsmpb_1_arg;
		cuda_occupancy_max_active_bpm_1_argument cuda_occupancy_max_active_bpm_1_arg;
		cuda_occupancy_max_active_bpm_with_flags_1_argument cuda_occupancy_max_active_bpm_with_flags_1_arg;
		ptr cuda_array_get_info_1_arg;
		ptr cuda_array_get_sparse_properties_1_arg;
		ptr cuda_free_1_arg;
		ptr cuda_free_array_1_arg;
		int cuda_free_host_1_arg;
		ptr cuda_get_symbol_address_1_arg;
		ptr cuda_get_symbol_size_1_arg;
		cuda_host_alloc_1_argument cuda_host_alloc_1_arg;
		cuda_host_get_device_pointer_1_argument cuda_host_get_device_pointer_1_arg;
		ptr cuda_host_get_flags_1_arg;
		size_t cuda_malloc_1_arg;
		cuda_malloc_3d_1_argument cuda_malloc_3d_1_arg;
		cuda_malloc_3d_array_1_argument cuda_malloc_3d_array_1_arg;
		cuda_malloc_array_1_argument cuda_malloc_array_1_arg;
		cuda_malloc_pitch_1_argument cuda_malloc_pitch_1_arg;
		cuda_mem_advise_1_argument cuda_mem_advise_1_arg;
		cuda_mem_prefetch_async_1_argument cuda_mem_prefetch_async_1_arg;
		cuda_memcpy_htod_1_argument cuda_memcpy_htod_1_arg;
		cuda_memcpy_dtoh_1_argument cuda_memcpy_dtoh_1_arg;
		cuda_memcpy_shm_1_argument cuda_memcpy_shm_1_arg;
		cuda_memcpy_dtod_1_argument cuda_memcpy_dtod_1_arg;
		cuda_memcpy_to_symbol_1_argument cuda_memcpy_to_symbol_1_arg;
		cuda_memcpy_to_symbol_shm_1_argument cuda_memcpy_to_symbol_shm_1_arg;
		cuda_memcpy_ib_1_argument cuda_memcpy_ib_1_arg;
		cuda_memset_1_argument cuda_memset_1_arg;
		cuda_memset_2d_1_argument cuda_memset_2d_1_arg;
		cuda_memset_3d_1_argument cuda_memset_3d_1_arg;
		cuda_device_can_access_peer_1_argument cuda_device_can_access_peer_1_arg;
		int cuda_device_disable_peer_access_1_arg;
		cuda_device_enable_peer_access_1_argument cuda_device_enable_peer_access_1_arg;
		int rpc_cuinit_1_arg;
		int rpc_cudeviceget_1_arg;
		int rpc_cudevicegetname_1_arg;
		int rpc_cudevicetotalmem_1_arg;
		rpc_cudevicegetattribute_1_argument rpc_cudevicegetattribute_1_arg;
		int rpc_cudevicegetuuid_1_arg;
		uint64_t rpc_cuctxsetcurrent_1_arg;
		int rpc_cudeviceprimaryctxretain_1_arg;
		rpc_cumodulegetfunction_1_argument rpc_cumodulegetfunction_1_arg;
		rpc_uuid rpc_cugetexporttable_1_arg;
		uint64_t rpc_cumemalloc_1_arg;
		rpc_cumemcpyhtod_1_argument rpc_cumemcpyhtod_1_arg;
		rpc_culaunchkernel_1_argument rpc_culaunchkernel_1_arg;
		int rpc_hidden_get_device_ctx_1_arg;
		rpc_hidden_get_module_1_argument rpc_hidden_get_module_1_arg;
		rpc_hidden_1_3_1_argument rpc_hidden_1_3_1_arg;
		uint64_t rpc_hidden_2_1_1_arg;
		rpc_hidden_3_0_1_argument rpc_hidden_3_0_1_arg;
		rpc_hidden_3_2_1_argument rpc_hidden_3_2_1_arg;
		rpc_cusolverdnsetstream_1_argument rpc_cusolverdnsetstream_1_arg;
		rpc_cusolverdndgetrf_buffersize_1_argument rpc_cusolverdndgetrf_buffersize_1_arg;
		rpc_cusolverdndgetrf_1_argument rpc_cusolverdndgetrf_1_arg;
		rpc_cusolverdndgetrs_1_argument rpc_cusolverdndgetrs_1_arg;
		ptr rpc_cusolverdndestroy_1_arg;
	} argument;
	union {
		int rpc_checkpoint_1_res;
		int rpc_deinit_1_res;
		int rpc_printmessage_1_res;
		int_result cuda_choose_device_1_res;
		int_result cuda_device_get_attribute_1_res;
		int_result cuda_device_get_by_pci_bus_id_1_res;
		int_result cuda_device_get_cache_config_1_res;
		u64_result cuda_device_get_limit_1_res;
		int_result cuda_device_get_p2p_attribute_1_res;
		str_result cuda_device_get_pci_bus_id_1_res;
		int_result cuda_device_get_shared_mem_config_1_res;
		dint_result cuda_device_get_stream_priority_range_1_res;
		u64_result cuda_device_get_texture_lmw_1_res;
		int cuda_device_reset_1_res;
		int cuda_device_set_cache_config_1_res;
		int cuda_device_set_limit_1_res;
		int cuda_device_set_shared_mem_config_1_res;
		int cuda_device_synchronize_1_res;
		int_result cuda_get_device_1_res;
		int_result cuda_get_device_count_1_res;
		int_result cuda_get_device_flags_1_res;
		mem_result cuda_get_device_properties_1_res;
		int cuda_set_device_1_res;
		int cuda_set_device_flags_1_res;
		int cuda_set_valid_devices_1_res;
		str_result cuda_get_error_name_1_res;
		str_result cuda_get_error_string_1_res;
		int cuda_get_last_error_1_res;
		int cuda_peek_at_last_error_1_res;
		int cuda_ctx_reset_persisting_l2cache_1_res;
		int cuda_stream_copy_attributes_1_res;
		ptr_result cuda_stream_create_1_res;
		ptr_result cuda_stream_create_with_flags_1_res;
		ptr_result cuda_stream_create_with_priority_1_res;
		int cuda_stream_destroy_1_res;
		int_result cuda_stream_get_flags_1_res;
		int_result cuda_stream_get_priority_1_res;
		int cuda_stream_query_1_res;
		int cuda_stream_synchronize_1_res;
		int cuda_stream_wait_event_1_res;
		int_result cuda_thread_exchange_stream_capture_mode_1_res;
		ptr_result cuda_event_create_1_res;
		ptr_result cuda_event_create_with_flags_1_res;
		int cuda_event_destroy_1_res;
		float_result cuda_event_elapsed_time_1_res;
		int cuda_event_query_1_res;
		int cuda_event_record_1_res;
		int cuda_event_record_with_flags_1_res;
		int cuda_event_synchronize_1_res;
		mem_result cuda_func_get_attributes_1_res;
		int cuda_func_set_attributes_1_res;
		int cuda_func_set_cache_config_1_res;
		int cuda_func_set_shared_mem_config_1_res;
		int cuda_launch_cooperative_kernel_1_res;
		int cuda_launch_cooperative_kernel_multi_device_1_res;
		int cuda_launch_kernel_1_res;
		u64_result cuda_occupancy_available_dsmpb_1_res;
		int_result cuda_occupancy_max_active_bpm_1_res;
		int_result cuda_occupancy_max_active_bpm_with_flags_1_res;
		mem_result cuda_array_get_info_1_res;
		mem_result cuda_array_get_sparse_properties_1_res;
		int cuda_free_1_res;
		int cuda_free_array_1_res;
		int cuda_free_host_1_res;
		ptr_result cuda_get_symbol_address_1_res;
		u64_result cuda_get_symbol_size_1_res;
		int cuda_host_alloc_1_res;
		ptr_result cuda_host_get_device_pointer_1_res;
		int_result cuda_host_get_flags_1_res;
		ptr_result cuda_malloc_1_res;
		pptr_result cuda_malloc_3d_1_res;
		ptr_result cuda_malloc_3d_array_1_res;
		ptr_result cuda_malloc_array_1_res;
		ptrsz_result cuda_malloc_pitch_1_res;
		int cuda_mem_advise_1_res;
		dsz_result cuda_mem_get_info_1_res;
		int cuda_mem_prefetch_async_1_res;
		int cuda_memcpy_htod_1_res;
		mem_result cuda_memcpy_dtoh_1_res;
		int cuda_memcpy_shm_1_res;
		int cuda_memcpy_dtod_1_res;
		int cuda_memcpy_to_symbol_1_res;
		int cuda_memcpy_to_symbol_shm_1_res;
		int cuda_memcpy_ib_1_res;
		int cuda_memset_1_res;
		int cuda_memset_2d_1_res;
		int cuda_memset_3d_1_res;
		int_result cuda_device_can_access_peer_1_res;
		int cuda_device_disable_peer_access_1_res;
		int cuda_device_enable_peer_access_1_res;
		int_result cuda_driver_get_version_1_res;
		int_result cuda_runtime_get_version_1_res;
		int_result rpc_cudevicegetcount_1_res;
		int rpc_cuinit_1_res;
		int_result rpc_cudrivergetversion_1_res;
		int_result rpc_cudeviceget_1_res;
		str_result rpc_cudevicegetname_1_res;
		u64_result rpc_cudevicetotalmem_1_res;
		int_result rpc_cudevicegetattribute_1_res;
		uuid_result rpc_cudevicegetuuid_1_res;
		ptr_result rpc_cuctxgetcurrent_1_res;
		int rpc_cuctxsetcurrent_1_res;
		ptr_result rpc_cudeviceprimaryctxretain_1_res;
		ptr_result rpc_cumodulegetfunction_1_res;
		ptr_result rpc_cugetexporttable_1_res;
		ptr_result rpc_cumemalloc_1_res;
		int_result rpc_cuctxgetdevice_1_res;
		int rpc_cumemcpyhtod_1_res;
		int rpc_culaunchkernel_1_res;
		ptr_result rpc_hidden_get_device_ctx_1_res;
		ptr_result rpc_hidden_get_module_1_res;
		ptr_result rpc_hidden_1_1_1_res;
		ptr_result rpc_hidden_1_5_1_res;
		int rpc_hidden_3_0_1_res;
		mem_result rpc_hidden_3_2_1_res;
		ptr_result rpc_cusolverdncreate_1_res;
		int rpc_cusolverdnsetstream_1_res;
		int_result rpc_cusolverdndgetrf_buffersize_1_res;
		int rpc_cusolverdndgetrf_1_res;
		int rpc_cusolverdndgetrs_1_res;
		int rpc_cusolverdndestroy_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case rpc_checkpoint:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_checkpoint_1;
		break;

	case rpc_deinit:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_deinit_1;
		break;

	case rpc_printmessage:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_printmessage_1;
		break;

	case CUDA_CHOOSE_DEVICE:
		_xdr_argument = (xdrproc_t) xdr_mem_data;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_choose_device_1;
		break;

	case CUDA_DEVICE_GET_ATTRIBUTE:
		_xdr_argument = (xdrproc_t) xdr_cuda_device_get_attribute_1_argument;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_attribute_1;
		break;

	case CUDA_DEVICE_GET_BY_PCI_BUS_ID:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_by_pci_bus_id_1;
		break;

	case CUDA_DEVICE_GET_CACHE_CONFIG:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_cache_config_1;
		break;

	case CUDA_DEVICE_GET_LIMIT:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_u64_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_limit_1;
		break;

	case CUDA_DEVICE_GET_P2P_ATTRIBUTE:
		_xdr_argument = (xdrproc_t) xdr_cuda_device_get_p2p_attribute_1_argument;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_p2p_attribute_1;
		break;

	case CUDA_DEVICE_GET_PCI_BUS_ID:
		_xdr_argument = (xdrproc_t) xdr_cuda_device_get_pci_bus_id_1_argument;
		_xdr_result = (xdrproc_t) xdr_str_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_pci_bus_id_1;
		break;

	case CUDA_DEVICE_GET_SHARED_MEM_CONFIG:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_shared_mem_config_1;
		break;

	case CUDA_DEVICE_GET_STREAM_PRIORITY_RANGE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_dint_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_stream_priority_range_1;
		break;

	case CUDA_DEVICE_GET_TEXTURE_LMW:
		_xdr_argument = (xdrproc_t) xdr_cuda_device_get_texture_lmw_1_argument;
		_xdr_result = (xdrproc_t) xdr_u64_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_get_texture_lmw_1;
		break;

	case CUDA_DEVICE_RESET:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_reset_1;
		break;

	case CUDA_DEVICE_SET_CACHE_CONFIG:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_set_cache_config_1;
		break;

	case CUDA_DEVICE_SET_LIMIT:
		_xdr_argument = (xdrproc_t) xdr_cuda_device_set_limit_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_set_limit_1;
		break;

	case CUDA_DEVICE_SET_SHARED_MEM_CONFIG:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_set_shared_mem_config_1;
		break;

	case CUDA_DEVICE_SYNCHRONIZE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_synchronize_1;
		break;

	case CUDA_GET_DEVICE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_device_1;
		break;

	case CUDA_GET_DEVICE_COUNT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_device_count_1;
		break;

	case CUDA_GET_DEVICE_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_device_flags_1;
		break;

	case CUDA_GET_DEVICE_PROPERTIES:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_mem_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_device_properties_1;
		break;

	case CUDA_SET_DEVICE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_set_device_1;
		break;

	case CUDA_SET_DEVICE_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_set_device_flags_1;
		break;

	case CUDA_SET_VALID_DEVICES:
		_xdr_argument = (xdrproc_t) xdr_cuda_set_valid_devices_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_set_valid_devices_1;
		break;

	case CUDA_GET_ERROR_NAME:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_str_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_error_name_1;
		break;

	case CUDA_GET_ERROR_STRING:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_str_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_error_string_1;
		break;

	case CUDA_GET_LAST_ERROR:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_last_error_1;
		break;

	case CUDA_PEEK_AT_LAST_ERROR:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_peek_at_last_error_1;
		break;

	case CUDA_CTX_RESET_PERSISTING_L2CACHE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_ctx_reset_persisting_l2cache_1;
		break;

	case CUDA_STREAM_COPY_ATTRIBUTES:
		_xdr_argument = (xdrproc_t) xdr_cuda_stream_copy_attributes_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_copy_attributes_1;
		break;

	case CUDA_STREAM_CREATE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_create_1;
		break;

	case CUDA_STREAM_CREATE_WITH_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_create_with_flags_1;
		break;

	case CUDA_STREAM_CREATE_WITH_PRIORITY:
		_xdr_argument = (xdrproc_t) xdr_cuda_stream_create_with_priority_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_create_with_priority_1;
		break;

	case CUDA_STREAM_DESTROY:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_destroy_1;
		break;

	case CUDA_STREAM_GET_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_get_flags_1;
		break;

	case CUDA_STREAM_GET_PRIORITY:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_get_priority_1;
		break;

	case CUDA_STREAM_QUERY:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_query_1;
		break;

	case CUDA_STREAM_SYNCHRONIZE:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_synchronize_1;
		break;

	case CUDA_STREAM_WAIT_EVENT:
		_xdr_argument = (xdrproc_t) xdr_cuda_stream_wait_event_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_stream_wait_event_1;
		break;

	case CUDA_THREAD_EXCHANGE_STREAM_CAPTURE_MODE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_thread_exchange_stream_capture_mode_1;
		break;

	case CUDA_EVENT_CREATE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_create_1;
		break;

	case CUDA_EVENT_CREATE_WITH_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_create_with_flags_1;
		break;

	case CUDA_EVENT_DESTROY:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_destroy_1;
		break;

	case CUDA_EVENT_ELAPSED_TIME:
		_xdr_argument = (xdrproc_t) xdr_cuda_event_elapsed_time_1_argument;
		_xdr_result = (xdrproc_t) xdr_float_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_elapsed_time_1;
		break;

	case CUDA_EVENT_QUERY:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_query_1;
		break;

	case CUDA_EVENT_RECORD:
		_xdr_argument = (xdrproc_t) xdr_cuda_event_record_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_record_1;
		break;

	case CUDA_EVENT_RECORD_WITH_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_cuda_event_record_with_flags_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_record_with_flags_1;
		break;

	case CUDA_EVENT_SYNCHRONIZE:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_event_synchronize_1;
		break;

	case CUDA_FUNC_GET_ATTRIBUTES:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_mem_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_func_get_attributes_1;
		break;

	case CUDA_FUNC_SET_ATTRIBUTES:
		_xdr_argument = (xdrproc_t) xdr_cuda_func_set_attributes_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_func_set_attributes_1;
		break;

	case CUDA_FUNC_SET_CACHE_CONFIG:
		_xdr_argument = (xdrproc_t) xdr_cuda_func_set_cache_config_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_func_set_cache_config_1;
		break;

	case CUDA_FUNC_SET_SHARED_MEM_CONFIG:
		_xdr_argument = (xdrproc_t) xdr_cuda_func_set_shared_mem_config_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_func_set_shared_mem_config_1;
		break;

	case CUDA_LAUNCH_COOPERATIVE_KERNEL:
		_xdr_argument = (xdrproc_t) xdr_cuda_launch_cooperative_kernel_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_launch_cooperative_kernel_1;
		break;

	case CUDA_LAUNCH_COOPERATIVE_KERNEL_MULTI_DEVICE:
		_xdr_argument = (xdrproc_t) xdr_cuda_launch_cooperative_kernel_multi_device_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_launch_cooperative_kernel_multi_device_1;
		break;

	case CUDA_LAUNCH_KERNEL:
		_xdr_argument = (xdrproc_t) xdr_cuda_launch_kernel_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_launch_kernel_1;
		break;

	case CUDA_OCCUPANCY_AVAILABLE_DSMPB:
		_xdr_argument = (xdrproc_t) xdr_cuda_occupancy_available_dsmpb_1_argument;
		_xdr_result = (xdrproc_t) xdr_u64_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_occupancy_available_dsmpb_1;
		break;

	case CUDA_OCCUPANCY_MAX_ACTIVE_BPM:
		_xdr_argument = (xdrproc_t) xdr_cuda_occupancy_max_active_bpm_1_argument;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_occupancy_max_active_bpm_1;
		break;

	case CUDA_OCCUPANCY_MAX_ACTIVE_BPM_WITH_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_cuda_occupancy_max_active_bpm_with_flags_1_argument;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_occupancy_max_active_bpm_with_flags_1;
		break;

	case CUDA_ARRAY_GET_INFO:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_mem_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_array_get_info_1;
		break;

	case CUDA_ARRAY_GET_SPARSE_PROPERTIES:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_mem_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_array_get_sparse_properties_1;
		break;

	case CUDA_FREE:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_free_1;
		break;

	case CUDA_FREE_ARRAY:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_free_array_1;
		break;

	case CUDA_FREE_HOST:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_free_host_1;
		break;

	case CUDA_GET_SYMBOL_ADDRESS:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_symbol_address_1;
		break;

	case CUDA_GET_SYMBOL_SIZE:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_u64_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_get_symbol_size_1;
		break;

	case CUDA_HOST_ALLOC:
		_xdr_argument = (xdrproc_t) xdr_cuda_host_alloc_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_host_alloc_1;
		break;

	case CUDA_HOST_GET_DEVICE_POINTER:
		_xdr_argument = (xdrproc_t) xdr_cuda_host_get_device_pointer_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_host_get_device_pointer_1;
		break;

	case CUDA_HOST_GET_FLAGS:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_host_get_flags_1;
		break;

	case CUDA_MALLOC:
		_xdr_argument = (xdrproc_t) xdr_size_t;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_malloc_1;
		break;

	case CUDA_MALLOC_3D:
		_xdr_argument = (xdrproc_t) xdr_cuda_malloc_3d_1_argument;
		_xdr_result = (xdrproc_t) xdr_pptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_malloc_3d_1;
		break;

	case CUDA_MALLOC_3D_ARRAY:
		_xdr_argument = (xdrproc_t) xdr_cuda_malloc_3d_array_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_malloc_3d_array_1;
		break;

	case CUDA_MALLOC_ARRAY:
		_xdr_argument = (xdrproc_t) xdr_cuda_malloc_array_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_malloc_array_1;
		break;

	case CUDA_MALLOC_PITCH:
		_xdr_argument = (xdrproc_t) xdr_cuda_malloc_pitch_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptrsz_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_malloc_pitch_1;
		break;

	case CUDA_MEM_ADVISE:
		_xdr_argument = (xdrproc_t) xdr_cuda_mem_advise_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_mem_advise_1;
		break;

	case CUDA_MEM_GET_INFO:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_dsz_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_mem_get_info_1;
		break;

	case CUDA_MEM_PREFETCH_ASYNC:
		_xdr_argument = (xdrproc_t) xdr_cuda_mem_prefetch_async_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_mem_prefetch_async_1;
		break;

	case CUDA_MEMCPY_HTOD:
		_xdr_argument = (xdrproc_t) xdr_cuda_memcpy_htod_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memcpy_htod_1;
		break;

	case CUDA_MEMCPY_DTOH:
		_xdr_argument = (xdrproc_t) xdr_cuda_memcpy_dtoh_1_argument;
		_xdr_result = (xdrproc_t) xdr_mem_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memcpy_dtoh_1;
		break;

	case CUDA_MEMCPY_SHM:
		_xdr_argument = (xdrproc_t) xdr_cuda_memcpy_shm_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memcpy_shm_1;
		break;

	case CUDA_MEMCPY_DTOD:
		_xdr_argument = (xdrproc_t) xdr_cuda_memcpy_dtod_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memcpy_dtod_1;
		break;

	case CUDA_MEMCPY_TO_SYMBOL:
		_xdr_argument = (xdrproc_t) xdr_cuda_memcpy_to_symbol_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memcpy_to_symbol_1;
		break;

	case CUDA_MEMCPY_TO_SYMBOL_SHM:
		_xdr_argument = (xdrproc_t) xdr_cuda_memcpy_to_symbol_shm_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memcpy_to_symbol_shm_1;
		break;

	case CUDA_MEMCPY_IB:
		_xdr_argument = (xdrproc_t) xdr_cuda_memcpy_ib_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memcpy_ib_1;
		break;

	case CUDA_MEMSET:
		_xdr_argument = (xdrproc_t) xdr_cuda_memset_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memset_1;
		break;

	case CUDA_MEMSET_2D:
		_xdr_argument = (xdrproc_t) xdr_cuda_memset_2d_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memset_2d_1;
		break;

	case CUDA_MEMSET_3D:
		_xdr_argument = (xdrproc_t) xdr_cuda_memset_3d_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_memset_3d_1;
		break;

	case CUDA_DEVICE_CAN_ACCESS_PEER:
		_xdr_argument = (xdrproc_t) xdr_cuda_device_can_access_peer_1_argument;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_can_access_peer_1;
		break;

	case CUDA_DEVICE_DISABLE_PEER_ACCESS:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_disable_peer_access_1;
		break;

	case CUDA_DEVICE_ENABLE_PEER_ACCESS:
		_xdr_argument = (xdrproc_t) xdr_cuda_device_enable_peer_access_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_device_enable_peer_access_1;
		break;

	case CUDA_DRIVER_GET_VERSION:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_driver_get_version_1;
		break;

	case CUDA_RUNTIME_GET_VERSION:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cuda_runtime_get_version_1;
		break;

	case rpc_cuDeviceGetCount:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudevicegetcount_1;
		break;

	case rpc_cuInit:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cuinit_1;
		break;

	case rpc_cuDriverGetVersion:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudrivergetversion_1;
		break;

	case rpc_cuDeviceGet:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudeviceget_1;
		break;

	case rpc_cuDeviceGetName:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_str_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudevicegetname_1;
		break;

	case rpc_cuDeviceTotalMem:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_u64_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudevicetotalmem_1;
		break;

	case rpc_cuDeviceGetAttribute:
		_xdr_argument = (xdrproc_t) xdr_rpc_cudevicegetattribute_1_argument;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudevicegetattribute_1;
		break;

	case rpc_cuDeviceGetUuid:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_uuid_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudevicegetuuid_1;
		break;

	case rpc_cuCtxGetCurrent:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cuctxgetcurrent_1;
		break;

	case rpc_cuCtxSetCurrent:
		_xdr_argument = (xdrproc_t) xdr_uint64_t;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cuctxsetcurrent_1;
		break;

	case rpc_cuDevicePrimaryCtxRetain:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cudeviceprimaryctxretain_1;
		break;

	case rpc_cuModuleGetFunction:
		_xdr_argument = (xdrproc_t) xdr_rpc_cumodulegetfunction_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cumodulegetfunction_1;
		break;

	case rpc_cuGetExportTable:
		_xdr_argument = (xdrproc_t) xdr_rpc_uuid;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cugetexporttable_1;
		break;

	case rpc_cuMemAlloc:
		_xdr_argument = (xdrproc_t) xdr_uint64_t;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cumemalloc_1;
		break;

	case rpc_cuCtxGetDevice:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cuctxgetdevice_1;
		break;

	case rpc_cuMemcpyHtoD:
		_xdr_argument = (xdrproc_t) xdr_rpc_cumemcpyhtod_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cumemcpyhtod_1;
		break;

	case rpc_cuLaunchKernel:
		_xdr_argument = (xdrproc_t) xdr_rpc_culaunchkernel_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_culaunchkernel_1;
		break;

	case rpc_hidden_get_device_ctx:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_get_device_ctx_1;
		break;

	case rpc_hidden_get_module:
		_xdr_argument = (xdrproc_t) xdr_rpc_hidden_get_module_1_argument;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_get_module_1;
		break;

	case rpc_hidden_1_1:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_1_1_1;
		break;

	case rpc_hidden_1_3:
		_xdr_argument = (xdrproc_t) xdr_rpc_hidden_1_3_1_argument;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_1_3_1;
		break;

	case rpc_hidden_1_5:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_1_5_1;
		break;

	case rpc_hidden_2_1:
		_xdr_argument = (xdrproc_t) xdr_uint64_t;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_2_1_1;
		break;

	case rpc_hidden_3_0:
		_xdr_argument = (xdrproc_t) xdr_rpc_hidden_3_0_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_3_0_1;
		break;

	case rpc_hidden_3_2:
		_xdr_argument = (xdrproc_t) xdr_rpc_hidden_3_2_1_argument;
		_xdr_result = (xdrproc_t) xdr_mem_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_hidden_3_2_1;
		break;

	case rpc_cusolverDnCreate:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ptr_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cusolverdncreate_1;
		break;

	case rpc_cusolverDnSetStream:
		_xdr_argument = (xdrproc_t) xdr_rpc_cusolverdnsetstream_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cusolverdnsetstream_1;
		break;

	case rpc_cusolverDnDgetrf_bufferSize:
		_xdr_argument = (xdrproc_t) xdr_rpc_cusolverdndgetrf_buffersize_1_argument;
		_xdr_result = (xdrproc_t) xdr_int_result;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cusolverdndgetrf_buffersize_1;
		break;

	case rpc_cusolverDnDgetrf:
		_xdr_argument = (xdrproc_t) xdr_rpc_cusolverdndgetrf_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cusolverdndgetrf_1;
		break;

	case rpc_cusolverDnDgetrs:
		_xdr_argument = (xdrproc_t) xdr_rpc_cusolverdndgetrs_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cusolverdndgetrs_1;
		break;

	case rpc_cusolverDnDestroy:
		_xdr_argument = (xdrproc_t) xdr_ptr;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_cusolverdndestroy_1;
		break;

	default:
		_xdr_argument = NULL;     _xdr_result = NULL;
    local = NULL;     }
*ret_arg = _xdr_argument;*ret_res = _xdr_result;*res_sz = sizeof(result); *ret_fun = local;}
