/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <stdlib.h>
#include <stdio.h>

#include "cd_rpc_prot.h"

#include <sys/socket.h>

extern void rpc_cd_prog_1(struct svc_req *rqstp, register SVCXPRT *transp);


bool_t printmessage_1_svc(char *argp, int *result, struct svc_req *rqstp)
{
    printf("string: \"%s\"\n", argp);
    *result = 42;
    return 1;
}

bool_t cudevicegetcount_1_svc(int_result *result, struct svc_req *rqstp)
{
    printf("called cudevicegetcount\n");
    result->err = 0;
    result->int_result_u.data = 5;
    return 1;
}

int rpc_cd_prog_1_freeresult (SVCXPRT * a, xdrproc_t b , caddr_t c)
{
}

int main (int argc, char **argv)
{
	register SVCXPRT *transp;

	transp = svcunix_create(RPC_ANYSOCK, 0, 0, "/home/work/testsock");
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create unix service.");
		exit(1);
	}
	if (!svc_register(transp, RPC_CD_PROG, RPC_CD_VERS, rpc_cd_prog_1, 0)) {
		fprintf (stderr, "%s", "unable to register (RPC_PROG_PROG, RPC_PROG_VERS, ).");
		exit(1);
	}
	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	return 0;
}
